version: "3"

services:
  bot:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    depends_on:
        - lavalink
    volumes:
      - ./:/usr/src/app
    command: cargo run
    environment:
      - RUST_LOG=trace
  lavalink:
    image: fredboat/lavalink:master
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    ports:
      - 2333:2333
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: passworddevelop
      POSTGRES_DB: sheepbot
    ports:
      - 5432:5432