FROM rust:slim-buster
ARG APP=/usr/src/app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    clang \
    curl \
    git \
    libavcodec-dev \
    libavdevice-dev \
    libavfilter-dev \
    libavformat-dev \
    libavresample-dev \
    libavutil-dev \
    libpostproc-dev \
    libswresample-dev \
    libswscale-dev \
    autoconf \
    autogen \
    libtool \
    automake \
    python3 \
    python3-pip \
    aria2 \
    openssl \
    libssl-dev \
    pkg-config


RUN mkdir -p ${APP}

WORKDIR ${APP}
